AWSTemplateFormatVersion: "2010-09-09"
Description: Create ECS Services.

Parameters:
  RepositoryName:
    Description: The name of the cluster.
    Type: String
    Default: ecr-demo
Resources:
  ServiceImageRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: !Ref RepositoryName

Outputs:
  StackName:
    Description: ECR nested stack name
    Value: !Sub "${AWS::StackName}"

  RepositoryUri:
    Description: ECR RepositoryUri
    Value: !GetAtt ServiceImageRepository.RepositoryUri
    Export:
      Name: !Sub "${AWS::StackName}-RepositoryUri"